//COUNTRIES & ACTIVITIES
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES'
export const GET_COUNTRIES_PER_PAGE = 'GET_COUNTRIES_PER_PAGE'
export const SEARCH_COUNTRIES = 'SEARCH_COUNTRIES'
export const FILTER_COUNTRIES_BY_CONTINENT = 'FILTER_COUNTRIES_BY_CONTINENT'
export const ORDER_COUNTRIES_BY_NAME = 'ORDER_COUNTRIES_BY_NAME'
export const ORDER_COUNTRIES_BY_POPULATION = 'ORDER_COUNTRIES_BY_POPULATION'

//ERROR
export const ERROR_SEARCH_COUNTRIES = 'ERROR_SEARCH_COUNTRIES'

//Coming soon
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGGED_IN_SUCCESS = 'LOGGED_IN_SUCCESS';
export const LOGGED_IN_FAIL = 'LOGGED_IN_FAIL';