export const IS_FETCHING = 'IS_FETCHING'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'

//COUNTRIES & ACTIVITIES
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES'
export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES'
export const GET_ALL_CONTINENTS = 'GET_ALL_CONTINENTS'
export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL'
export const CLEAR_COUNTRY_DETAIL = 'CLEAR_COUNTRY_DETAIL'
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY'

//SEARCH
export const SET_SEARCH = 'SET_SEARCH'
export const SEARCH_COUNTRIES = 'SEARCH_COUNTRIES'

//FILTERS
export const SET_FILTER_COUNTRIES = 'SET_FILTER_COUNTRIES'
export const FILTER_COUNTRIES = 'FILTER_COUNTRIES'

//SORTS
export const SET_SORT_COUNTRIES = 'SET_SORT_COUNTRIES'
export const SORT_COUNTRIES = 'SORT_COUNTRIES'

//ERROR
export const ERROR_SEARCH_COUNTRIES = 'ERROR_SEARCH_COUNTRIES'
export const ERROR_GET_COUNTRY_DETAIL = 'ERROR_GET_COUNTRY_DETAIL'
export const ERROR_CREATE_ACTIVITY = 'ERROR_CREATE_ACTIVITY'

//EXTRAS
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY'
export const MODIFIED_ACTIVITY = 'MODIFIED_ACTIVITY'
export const ERROR_DELETE_ACTIVITY = 'ERROR_DELETE_ACTIVITY'
export const ERROR_MODIFIED_ACTIVITY = 'ERROR_MODIFIED_ACTIVITY'
export const SHOW_MODAL = 'SHOW_MODAL'
export const SET_TYPE_MODAL = 'SET_TYPE_MODAL'


//Coming soon
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGGED_IN_SUCCESS = 'LOGGED_IN_SUCCESS';
export const LOGGED_IN_FAIL = 'LOGGED_IN_FAIL';