export const IS_FETCHING = 'IS_FETCHING'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'

//COUNTRIES & ACTIVITIES
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES'
export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES'
export const SEARCH_COUNTRIES = 'SEARCH_COUNTRIES'
export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL'
export const CLEAR_COUNTRY_DETAIL = 'CLEAR_COUNTRY_DETAIL'

export const SORT_COUNTRIES = 'SORT_COUNTRIES'


// export const FILTER_COUNTRIES_BY_CONTINENT = 'FILTER_COUNTRIES_BY_CONTINENT'
// export const FILTER_COUNTRIES_BY_ACTIVITY = 'FILTER_COUNTRIES_BY_ACTIVITY'
// export const ORDER_COUNTRIES_BY_NAME = 'ORDER_COUNTRIES_BY_NAME'
// export const ORDER_COUNTRIES_BY_POPULATION = 'ORDER_COUNTRIES_BY_POPULATION'

//ERROR
export const ERROR_SEARCH_COUNTRIES = 'ERROR_SEARCH_COUNTRIES'

//Coming soon
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGGED_IN_SUCCESS = 'LOGGED_IN_SUCCESS';
export const LOGGED_IN_FAIL = 'LOGGED_IN_FAIL';